### ISSUE TITLE
How to customize the maven repository?

### ISSUE THREAD

**Issue by jsvd** [torquebox/maven-tools#9]
According to https://github.com/torquebox/maven-tools/blob/793dae8d98f5187cf04cc54f1b22665ff7ec29c5/spec/dsl/project_gemspec_spec/extended.gemspec it's possible to specify a custom maven repo, but when I do it in a gem:

`s.requirements << "repo 'http://localhost/repo'"`

I get

`unknown declaration: repo 'http://localhost/repo'`

I also tried `repository`, `source`. Using maven tools 1.0.7 and jar-dependencies 0.1.7

**Comment by mkristian** [comment]
see how to get this test works:
https://github.com/torquebox/maven-tools/blob/793dae8d98f5187cf04cc54f1b22665ff7ec29c5/spec/dsl/project_gemspec_spec.rb#L85

it is meant for some closed environment to patch maven-tools to allow those repo declaration.

in general this is not possible, the original idea was:

* all gems come from rubygems.org
* all jars come from maven-central

just recently I learned about jcenter from gradle but not sure whether this will be coming.

but a general repo will NOT come - maven had too much problems still has with artifacts using a repo which does not exist anymore or not having those artifacts anymore. maven-central does not delete anything even totally broken ones.

**Comment by jsvd** [comment]
Thank you for the quick response.

I'm getting:

No connector available to access repository 'http://localhost' of type default using the available factories WagonRepositoryConnectorFactory -> [Help 1]

is this an issue w/ my repo?

**Comment by mkristian** [comment]
could you set JARS_DEBUG=true and give me the output to see what is going on

**Comment by jsvd** [comment]
Fixed. An issue on my side, missing metadata. Thank you for the feedback.
